### ISSUE TITLE
detection_inference.py

### ISSUE THREAD

**Issue by LMcHill** [miguel55/ACME#3]
Hi!

Maybe you can help me again by generating the results_test.mat file in Step 4 that is needed in the further proceedings.
By executing detection_inference.py I need to import several libraries. However, importing roi_al_extension and roi_al_extension_3D fails, and I don't know where to download this extension and how I can add it to python.

Best wishes and thank you in advance :)

**Comment by miguel55** [comment]
You have to compile it as shown in the requirements section. 

I hope that it helps!
