### ISSUE TITLE
The setup_roi_align.py program seems to be missing the required files.

### ISSUE THREAD

**Issue by AYuLiQing** [miguel55/ACME#4]
Hello, I have encountered a problem in the process of using your program.
While compiling the functions in the custom_extensions folder through the setup_roi_align.py script, The setup_roi_align.py program needs the dist folder in the custom_extensions/roi_align/2D and custom_extensions/roi_align/3D folders, And files with a.whl suffix in the dist folder.
But I haven't found any of that so far.

**Comment by miguel55** [comment]
Hello, 

Your compilation may have failed and the code is trying to load pre-compiled files. Please check that CUDA_HOME points to your CUDA installation and the complete error trace for the failed compilation.

I hope that it helps you.

**Comment by AYuLiQing** [comment]
Thank you for your response.   The previous issue has been resolved.   When I run the script process_ACME_segmentations.  m later, there is the following code:
dataLa = ['results/', aux{end-1}, '/', aux{end}, '_La'];
load([dataLa, filesep, 'T', sprintf('%05d', j), '.mat']);
However, I could not find the corresponding file.   Before these two lines of code, there is a segment of code as follows:
if (~exist(['results/', aux{end-1},'/', aux{end}, '_La'], 'dir'))
mkdir(['results/', aux{end-1}, '/', aux{end}, '_La']);
It seems that this folder has just been created, and the first section of code attempts to find files in it, which is a bit confusing to me.

> Hello,
> 
> Your compilation may have failed and the code is trying to load pre-compiled files. Please check that CUDA_HOME points to your CUDA installation and the complete error trace for the failed compilation.
> 
> I hope that it helps you.

**Comment by miguel55** [comment]
Hello, 

This is something just to visualize the results, it reads the .mat segmentations and creates images with them. You can put the JPG param to False in the config.m file if you do not want to visualize it. In any case, after the 3D 3-pass tracking, these folders should contain the .mat files with the cells tracked (they are segmentations with the same identifier across temporal instants for the same cell).
